const fs = require('fs');
const assert = require('assert');
const source = fs.readFileSync('rider/rider-app.js', 'utf8');
assert.match(source, /async function login\(\)/, 'Rider ต้องมี login flow');
assert.match(source, /aria-label="อีเมล"/, 'Rider login ต้องคง label สำหรับ accessibility');
assert.match(source, /aria-label="รหัสผ่าน"/, 'Rider login ต้องคง label สำหรับ accessibility');
assert.match(source, /href="\.\.\/rider\.html"/, 'Rider ต้องคง fallback link เดิมเป็น escape hatch');
assert.match(source, /aria-label="เปิดหน้าไรเดอร์แบบเดิม"/, 'Rider fallback ต้องคง accessibility label');
assert.doesNotMatch(source, /ใช้บัญชีไรเดอร์ที่ได้รับสิทธิ์ใน AP Service/, 'Rider login ต้องไม่มีข้อความระบบ');
console.log('rider login minimal shell contract: PASS');
